// @generated by protoc-gen-es v1.9.0
// @generated from file zitadel/feature.proto (package zitadel.feature.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum zitadel.feature.v1.InstanceFeature
 */
export const InstanceFeature = /*@__PURE__*/ proto3.makeEnum(
  "zitadel.feature.v1.InstanceFeature",
  [
    {no: 0, name: "INSTANCE_FEATURE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "INSTANCE_FEATURE_LOGIN_DEFAULT_ORG", localName: "LOGIN_DEFAULT_ORG"},
  ],
);

