# Always validate the PR title, and ignore the commits
titleOnly: true

# Allowed types — the PR title type must be one of these.
# This list is the single source of truth referenced by AGENTS.md and CONTRIBUTING.md.
types:
  - feat      # new feature
  - fix       # bug fix
  - docs      # documentation only (no code change)
  - refactor  # code restructuring without behaviour change
  - perf      # performance improvement
  - test      # adding or fixing tests
  - build     # build system or tooling
  - ci        # CI/CD pipeline
  - chore     # maintenance (deps, config, etc.)
  - revert    # reverts a previous commit

# Allowed scopes — if a scope is provided it must match one of these.
# Scopes are optional; omit rather than invent one not on this list.
# Note: 'docs' is a type, not a scope — use the type 'docs' for documentation changes.
# This list is the single source of truth referenced by AGENTS.md and CONTRIBUTING.md.
scopes:
  # Backend — domain areas
  - api
  - session
  - authz
  - command
  - query
  - eventstore
  - actions
  - crypto
  - domain
  - feature
  - idp
  - notification
  - oidc
  - saml
  - webauthn
  # Backend — infrastructure
  - cache
  - config
  - database
  - migration
  - setup
  - telemetry
  - queue
  # Frontend
  - console
  - login
  # API layer
  - grpc
  - proto
  # Cross-cutting
  - build
  - ci
  - deps
  - i18n
  - integration
  - perf
  - security
  - test
