version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - exhaustive
    - gocognit
    - gocritic
    - misspell
    - nakedret
    - nolintlint
    - nosprintfhostport
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - nilnil
  disable:
    - bidichk
    - containedctx
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mnd
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .artifacts
      - .backups
      - .codecov
      - .github
      - .keys
      - .vscode
      - build
      - console
      - deploy
      - docs
      - guides
      - internal/api/ui/login/static
      - openapi
      - proto
      - tools
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: main
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/zitadel/zitadel)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - .artifacts
      - .backups
      - .codecov
      - .github
      - .keys
      - .vscode
      - build
      - console
      - deploy
      - docs
      - guides
      - internal/api/ui/login/static
      - openapi
      - proto
      - tools
      - third_party$
      - builtin$
      - examples$
