packages:
  - docs
  - console
  - release
  - tests/*
  - packages/*
  - apps/*
  - apps/login/integration/api-mock

exclude:
  - benchmark # because of the node 18 or 20 dependency

overrides:
  '@typescript-eslint/parser': '^8.35.1'
