// Code generated by "enumer -type=DetectorType -trimprefix=DetectorType -text -linecomment"; DO NOT EDIT.

package instrumentation

import (
	"fmt"
	"strings"
)

const _DetectorTypeName = "Google"

var _DetectorTypeIndex = [...]uint8{0, 0, 6}

const _DetectorTypeLowerName = "google"

func (i DetectorType) String() string {
	if i < 0 || i >= DetectorType(len(_DetectorTypeIndex)-1) {
		return fmt.Sprintf("DetectorType(%d)", i)
	}
	return _DetectorTypeName[_DetectorTypeIndex[i]:_DetectorTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DetectorTypeNoOp() {
	var x [1]struct{}
	_ = x[DetectorTypeUnspecified-(0)]
	_ = x[DetectorTypeGoogle-(1)]
}

var _DetectorTypeValues = []DetectorType{DetectorTypeUnspecified, DetectorTypeGoogle}

var _DetectorTypeNameToValueMap = map[string]DetectorType{
	_DetectorTypeName[0:0]:      DetectorTypeUnspecified,
	_DetectorTypeLowerName[0:0]: DetectorTypeUnspecified,
	_DetectorTypeName[0:6]:      DetectorTypeGoogle,
	_DetectorTypeLowerName[0:6]: DetectorTypeGoogle,
}

var _DetectorTypeNames = []string{
	_DetectorTypeName[0:0],
	_DetectorTypeName[0:6],
}

// DetectorTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DetectorTypeString(s string) (DetectorType, error) {
	if val, ok := _DetectorTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DetectorTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DetectorType values", s)
}

// DetectorTypeValues returns all values of the enum
func DetectorTypeValues() []DetectorType {
	return _DetectorTypeValues
}

// DetectorTypeStrings returns a slice of all String values of the enum
func DetectorTypeStrings() []string {
	strs := make([]string, len(_DetectorTypeNames))
	copy(strs, _DetectorTypeNames)
	return strs
}

// IsADetectorType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DetectorType) IsADetectorType() bool {
	for _, v := range _DetectorTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for DetectorType
func (i DetectorType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DetectorType
func (i *DetectorType) UnmarshalText(text []byte) error {
	var err error
	*i, err = DetectorTypeString(string(text))
	return err
}
