// Code generated by "enumer -type=ExporterType -trimprefix=OtelExporterType -text -linecomment"; DO NOT EDIT.

package instrumentation

import (
	"fmt"
	"strings"
)

const _ExporterTypeName = "ExporterTypeNoneExporterTypeStdOutExporterTypeStdErrExporterTypeGRPCExporterTypeHTTPExporterTypeGoogleExporterTypePrometheus"

var _ExporterTypeIndex = [...]uint8{0, 0, 16, 34, 52, 68, 84, 102, 124}

const _ExporterTypeLowerName = "exportertypenoneexportertypestdoutexportertypestderrexportertypegrpcexportertypehttpexportertypegoogleexportertypeprometheus"

func (i ExporterType) String() string {
	if i < 0 || i >= ExporterType(len(_ExporterTypeIndex)-1) {
		return fmt.Sprintf("ExporterType(%d)", i)
	}
	return _ExporterTypeName[_ExporterTypeIndex[i]:_ExporterTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ExporterTypeNoOp() {
	var x [1]struct{}
	_ = x[ExporterTypeUnspecified-(0)]
	_ = x[ExporterTypeNone-(1)]
	_ = x[ExporterTypeStdOut-(2)]
	_ = x[ExporterTypeStdErr-(3)]
	_ = x[ExporterTypeGRPC-(4)]
	_ = x[ExporterTypeHTTP-(5)]
	_ = x[ExporterTypeGoogle-(6)]
	_ = x[ExporterTypePrometheus-(7)]
}

var _ExporterTypeValues = []ExporterType{ExporterTypeUnspecified, ExporterTypeNone, ExporterTypeStdOut, ExporterTypeStdErr, ExporterTypeGRPC, ExporterTypeHTTP, ExporterTypeGoogle, ExporterTypePrometheus}

var _ExporterTypeNameToValueMap = map[string]ExporterType{
	_ExporterTypeName[0:0]:          ExporterTypeUnspecified,
	_ExporterTypeLowerName[0:0]:     ExporterTypeUnspecified,
	_ExporterTypeName[0:16]:         ExporterTypeNone,
	_ExporterTypeLowerName[0:16]:    ExporterTypeNone,
	_ExporterTypeName[16:34]:        ExporterTypeStdOut,
	_ExporterTypeLowerName[16:34]:   ExporterTypeStdOut,
	_ExporterTypeName[34:52]:        ExporterTypeStdErr,
	_ExporterTypeLowerName[34:52]:   ExporterTypeStdErr,
	_ExporterTypeName[52:68]:        ExporterTypeGRPC,
	_ExporterTypeLowerName[52:68]:   ExporterTypeGRPC,
	_ExporterTypeName[68:84]:        ExporterTypeHTTP,
	_ExporterTypeLowerName[68:84]:   ExporterTypeHTTP,
	_ExporterTypeName[84:102]:       ExporterTypeGoogle,
	_ExporterTypeLowerName[84:102]:  ExporterTypeGoogle,
	_ExporterTypeName[102:124]:      ExporterTypePrometheus,
	_ExporterTypeLowerName[102:124]: ExporterTypePrometheus,
}

var _ExporterTypeNames = []string{
	_ExporterTypeName[0:0],
	_ExporterTypeName[0:16],
	_ExporterTypeName[16:34],
	_ExporterTypeName[34:52],
	_ExporterTypeName[52:68],
	_ExporterTypeName[68:84],
	_ExporterTypeName[84:102],
	_ExporterTypeName[102:124],
}

// ExporterTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ExporterTypeString(s string) (ExporterType, error) {
	if val, ok := _ExporterTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ExporterTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ExporterType values", s)
}

// ExporterTypeValues returns all values of the enum
func ExporterTypeValues() []ExporterType {
	return _ExporterTypeValues
}

// ExporterTypeStrings returns a slice of all String values of the enum
func ExporterTypeStrings() []string {
	strs := make([]string, len(_ExporterTypeNames))
	copy(strs, _ExporterTypeNames)
	return strs
}

// IsAExporterType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ExporterType) IsAExporterType() bool {
	for _, v := range _ExporterTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for ExporterType
func (i ExporterType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ExporterType
func (i *ExporterType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ExporterTypeString(string(text))
	return err
}
