FirstInstance:
  PatPath: ./zitadel-admin-sa.pat
  LoginClientPatPath: ./login-client-sa.pat
  Org:
    Human:
      UserName: zitadel-admin
      FirstName: ZITADEL
      LastName: Admin
      Password: Password1!
      PasswordChangeRequired: false
      PreferredLanguage: en
    Machine:
      Machine:
        Username: zitadel-admin-sa
        Name: Admin
      Pat.ExpirationDate: 2099-01-01T00:00:00Z
    LoginClient:
      Machine:
        Username: login-client-sa
        Name: Login Client
      Pat.ExpirationDate: 2099-01-01T00:00:00Z

ExternalSecure: false
TLS:
  Enabled: false

OIDC:
  DefaultLoginURLV2: "http://localhost:3000/ui/v2/login/login?authRequest=" # ZITADEL_OIDC_DEFAULTLOGINURLV2
  DefaultLogoutURLV2: "http://localhost:3000/ui/v2/login/logout?post_logout_redirect=" # ZITADEL_OIDC_DEFAULTLOGOUTURLV2

SAML:
  DefaultLoginURLV2: "http://localhost:3000/ui/v2/login/login?samlRequest=" # ZITADEL_SAML_DEFAULTLOGINURLV2

Database:
  postgres:
    MaxOpenConns: 20
    MaxIdleConns: 20
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    User:
      Password: zitadel
      SSL:
        Mode: disable
    Admin:
      Username: zitadel
      SSL:
        Mode: disable

DefaultInstance:
  Features:
    TokenExchange: true
    LoginDefaultOrg: true # ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINDEFAULTORG
    LoginV2:
      Required: true # ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED
     # BaseURI: 'http://localhost:3000/ui/v2/login'
  LoginPolicy:
    AllowUsernamePassword: true # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_ALLOWUSERNAMEPASSWORD
    AllowRegister: true # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_ALLOWREGISTER
    AllowExternalIDP: true # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_ALLOWEXTERNALIDP
    ForceMFA: false # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_FORCEMFA
    HidePasswordReset: false # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_HIDEPASSWORDRESET
    IgnoreUnknownUsernames: false # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_IGNOREUNKNOWNUSERNAMES
    AllowDomainDiscovery: true # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_ALLOWDOMAINDISCOVERY
    # 1 is allowed, 0 is not allowed
    PasswordlessType: 1 # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_PASSWORDLESSTYPE
    # DefaultRedirectURL is empty by default because we use the Console UI
    DefaultRedirectURI: # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_DEFAULTREDIRECTURI
    # 240h = 10d
    PasswordCheckLifetime: 240h # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_PASSWORDCHECKLIFETIME
    # 240h = 10d
    ExternalLoginCheckLifetime: 240h # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_EXTERNALLOGINCHECKLIFETIME
    # 720h = 30d
    MfaInitSkipLifetime: 0h # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_MFAINITSKIPLIFETIME
    SecondFactorCheckLifetime: 18h # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_SECONDFACTORCHECKLIFETIME
    MultiFactorCheckLifetime: 12h # ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_MULTIFACTORCHECKLIFETIME
  PrivacyPolicy:
    TOSLink: "https://zitadel.com/docs/legal/terms-of-service"
    PrivacyLink: "https://zitadel.com/docs/legal/policies/privacy-policy"
    HelpLink: "https://zitadel.com/docs"
    SupportEmail: "support@zitadel.com"
    DocsLink: "https://zitadel.com/docs"

Login:
  DefaultPaths:
    BasePath: "/ui/v2/login"
    PasswordSetPath: "/password/set?code={{.Code}}&userId={{.UserID}}&organization={{.OrgID}}"
    EmailCodePath: "/verify?code={{.Code}}&userId={{.UserID}}&organization={{.OrgID}}"
    OTPEmailPath: "/otp/verify?code={{.Code}}&userID={{.UserID}}&sessionId={{.SessionID}}"