version: '3.8'

services:
  cockroach:
    extends:
      file: '../../../e2e/config/localhost/docker-compose.yaml'
      service: 'db'
  
  postgres:
    restart: 'always'
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=zitadel
      - PGUSER=zitadel
      - POSTGRES_DB=zitadel
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c shared_buffers=1GB -c work_mem=16MB -c effective_io_concurrency=100 -c wal_level=minimal -c archive_mode=off -c max_wal_senders=0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - 5432:5432

  cache:
    restart: 'always'
    image: 'redis:latest'
    ports:
      - 6379:6379
