Database:
  postgres:
    MaxOpenConns: 10
    MaxIdleConns: 8
    User:
      Password: zitadel
      SSL:
        Mode: disable
    Admin:
      Username: adlerhurst
      Password: password
      SSL:
        Mode: disable
