Database:
  postgres:
    MaxOpenConns: 20
    MaxIdleConns: 20
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    User:
      Password: zitadel
      SSL:
        Mode: disable
    Admin:
      Username: zitadel
      SSL:
        Mode: disable
