FirstInstance:
  Skip: false
  PatPath: tmp/admin-pat.txt
  InstanceName: ZITADEL
  DefaultLanguage: en
  Org:
    Name: ZITADEL
    Machine:
      Machine:
        Username: boss
        Name: boss
      Pat:
        ExpirationDate: 2099-01-01T00:00:00Z
