import { defineConfig, Options } from "tsup";

export default defineConfig((options: Options) => ({
  entry: {
    index: "src/index.ts",
    "auth/index": "src/auth/index.ts",
    "auth/oidc": "src/auth/oidc.ts",
    "auth/session": "src/auth/session.ts",
    cli: "src/cli/index.ts",
    middleware: "src/middleware.ts",
    "server-action": "src/server-action.ts",
    api: "src/api.ts",
    "api/bearer-token": "src/api/bearer-token.ts",
    webhook: "src/webhook.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  external: [
    "next",
    "next/headers",
    "next/navigation",
    "next/server",
    "react",
    "react-dom",
    "@zitadel/zitadel-js",
    "@zitadel/zitadel-js/auth/oidc",
    "@zitadel/zitadel-js/auth/session",
    "@zitadel/zitadel-js/api/bearer-token",
    "@zitadel/zitadel-js/v2",
    "@zitadel/zitadel-js/webhooks",
    "@zitadel/zitadel-js/node",
    "@zitadel/react",
  ],
  ...options,
}));
