services:

  db:
    extends:
      file: '../localhost/docker-compose.yaml'
      service: 'db'

  zitadel:
    depends_on:
      db:
        condition: 'service_healthy'
    extends:
      file: '../localhost/docker-compose.yaml'
      service: 'zitadel'
    volumes:
      - ./zitadel.yaml:/zitadel.yaml
  e2e:
    image: cypress/included:12.2.0
    depends_on:
      zitadel:
        condition: 'service_healthy'
      db:
        condition: 'service_healthy'
    working_dir: /e2e
    user: '$UID'
    volumes:
      - ../../:/e2e
    environment:
      CYPRESS_BASE_URL: http://host.docker.internal:8080/ui/console
      CYPRESS_WEBHOOK_HANDLER_HOST: host.docker.internal
      CYPRESS_DATABASE_CONNECTION_URL: 'postgresql://root@db:26257/zitadel'
    ports:
      - "8900:8900"
    extra_hosts:
    - "host.docker.internal:host-gateway"
