// Code generated by protoc-gen-authmethod. DO NOT EDIT.

package system

import (
	"github.com/zitadel/zitadel/internal/api/authz"
)

/**
 * SystemService
 */

const SystemService_MethodPrefix = "zitadel.system.v1.SystemService"

var SystemService_AuthMethods = authz.MethodMapping{

	"/zitadel.system.v1.SystemService/ListInstances": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/GetInstance": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/AddInstance": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/UpdateInstance": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/CreateInstance": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/RemoveInstance": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/ListIAMMembers": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/ExistsDomain": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/ListDomains": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/AddDomain": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/RemoveDomain": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/SetPrimaryDomain": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/ListViews": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/ClearView": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/ListFailedEvents": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/RemoveFailedEvent": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/AddQuota": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/zitadel.system.v1.SystemService/RemoveQuota": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},
}
