services:

  proxy-disabled-tls:
    image: "nginx:mainline-alpine"
    volumes:
      - "./nginx-disabled-tls.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    networks:
      - 'zitadel'
    depends_on:
      zitadel-disabled-tls:
        condition: 'service_healthy'

  proxy-external-tls:
    image: "nginx:mainline-alpine"
    volumes:
      - "./nginx-external-tls.conf:/etc/nginx/nginx.conf:ro"
      - "./selfsigned.crt:/etc/certs/selfsigned.crt:ro"
      - "./selfsigned.key:/etc/certs/selfsigned.key:ro"
    ports:
      - "443:443"
    networks:
      - 'zitadel'
    depends_on:
      zitadel-external-tls:
        condition: 'service_healthy'

  proxy-enabled-tls:
    image: "nginx:mainline-alpine"
    volumes:
      - "./nginx-enabled-tls.conf:/etc/nginx/nginx.conf:ro"
      - "./selfsigned.crt:/etc/certs/selfsigned.crt:ro"
      - "./selfsigned.key:/etc/certs/selfsigned.key:ro"
    ports:
      - "443:443"
    networks:
      - 'zitadel'
    depends_on:
      zitadel-enabled-tls:
        condition: 'service_healthy'

networks:
  zitadel: