CREATE SCHEMA IF NOT EXISTS signals;

GRANT USAGE, CREATE ON SCHEMA signals TO "%[1]s";
GRANT ALL ON ALL TABLES IN SCHEMA signals TO "%[1]s";
ALTER DEFAULT PRIVILEGES IN SCHEMA signals GRANT ALL ON TABLES TO "%[1]s";
