Log:
  Level: info

ExternalDomain: localhost
ExternalSecure: false

Database:
  postgres:
    # This makes the e2e config reusable with an out-of-docker zitadel process and an /etc/hosts entry
    Host: host.docker.internal
    Port: 5432
    database: zitadel
    MaxOpenConns: 15
    MaxIdleConns: 10
    Database: zitadel
    User:
      Username: zitadel
      Password: zitadel
      SSL:
        Mode: disable
    Admin:
      Username: postgres
      Password: postgres
      SSL:
        Mode: disable

TLS:
  Enabled: false

FirstInstance:
  Org:
    Human:
      PasswordChangeRequired: false

Console:
  InstanceManagementURL: "https://example.com/instances/{{.InstanceID}}"

Projections:
  Customizations:
    NotificationsQuotas:
      RequeueEvery: 1s

Quotas:
  Access:
    Enabled: true
    Debounce:
      MinFrequency: 0s
      MaxBulkSize: 0
    ExhaustedCookieKey: "zitadel.quota.limiting"
    ExhaustedCookieMaxAge: "600s"

DefaultInstance:
  LoginPolicy:
    MfaInitSkipLifetime: "0"

SystemAPIUsers:
- cypress:
    KeyData: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6aStGRlNKTDdmNXl3NEtUd3pnTQpQMzRlUEd5Y20vTStrVDBNN1Y0Q2d4NVYzRWFESXZUUUtUTGZCYUVCNDV6YjlMdGpJWHpEdzByWFJvUzJoTzZ0CmgrQ1lRQ3ozS0N2aDA5QzBJenhaaUIySVMzSC9hVCs1Qng5RUZZK3ZuQWtaamNjYnlHNVlOUnZtdE9sbnZJZUkKSDdxWjB0RXdrUGZGNUdFWk5QSlB0bXkzVUdWN2lvZmRWUVMxeFJqNzMrYU13NXJ2SDREOElkeWlBQzNWZWtJYgpwdDBWajBTVVgzRHdLdG9nMzM3QnpUaVBrM2FYUkYwc2JGaFFvcWRKUkk4TnFnWmpDd2pxOXlmSTV0eXhZc3duCitKR3pIR2RIdlczaWRPRGxtd0V0NUsycGFzaVJJV0syT0dmcSt3MEVjbHRRSGFidXFFUGdabG1oQ2tSZE5maXgKQndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

