/**
 * @fileoverview gRPC-Web generated client stub for zitadel.org.v2beta
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: zitadel/org/v2beta/org_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as zitadel_org_v2beta_org_service_pb from '../../../zitadel/org/v2beta/org_service_pb'; // proto import: "zitadel/org/v2beta/org_service.proto"


export class OrganizationServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAddOrganization = new grpcWeb.MethodDescriptor(
    '/zitadel.org.v2beta.OrganizationService/AddOrganization',
    grpcWeb.MethodType.UNARY,
    zitadel_org_v2beta_org_service_pb.AddOrganizationRequest,
    zitadel_org_v2beta_org_service_pb.AddOrganizationResponse,
    (request: zitadel_org_v2beta_org_service_pb.AddOrganizationRequest) => {
      return request.serializeBinary();
    },
    zitadel_org_v2beta_org_service_pb.AddOrganizationResponse.deserializeBinary
  );

  addOrganization(
    request: zitadel_org_v2beta_org_service_pb.AddOrganizationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<zitadel_org_v2beta_org_service_pb.AddOrganizationResponse>;

  addOrganization(
    request: zitadel_org_v2beta_org_service_pb.AddOrganizationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: zitadel_org_v2beta_org_service_pb.AddOrganizationResponse) => void): grpcWeb.ClientReadableStream<zitadel_org_v2beta_org_service_pb.AddOrganizationResponse>;

  addOrganization(
    request: zitadel_org_v2beta_org_service_pb.AddOrganizationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: zitadel_org_v2beta_org_service_pb.AddOrganizationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/zitadel.org.v2beta.OrganizationService/AddOrganization',
        request,
        metadata || {},
        this.methodDescriptorAddOrganization,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/zitadel.org.v2beta.OrganizationService/AddOrganization',
    request,
    metadata || {},
    this.methodDescriptorAddOrganization);
  }

}

