apiVersion: caos.ch/v1
kind: Zitadel
metadata:
  # This value must be zitadel
  name: zitadel
  # This value must be caos-system
  namespace: caos-system
spec:
  kind: zitadel.caos.ch/Orb
  version: v0
  spec:
    # Print debug logs
    verbose: false
    # This is the version of the ZITADEL operator deployment and the ZITADEL binary deployment
    version: 1.0.0
    # If true, the operator overwrites its own deployment using the version above
    selfReconciling: true
  iam:
    kind: zitadel.caos.ch/ZITADEL
    version: v0
    spec:
      # Print debug logs
      verbose: false
      # If true, Kubernetes resources are applied forcefully
      force: false
      # Number of ZITADEL pods
      replicaCount: 1
      # ZITADEL deployment configuration
      configuration:
        cache:
          maxAge: 12h
          sharedMaxAge: 168h
          shortMaxAge: 5m
          shortSharedMaxAge: 15m
        # Keys ZITADEL uses for symmetric encryption
        secrets:
          existingKeys:
            key: keys
            name: zitadel
          userVerificationID: userverificationkey_1
          otpVerificationID: otpverificationkey_1
          oidcKeysID: oidckey_1
          cookieID: cookiekey_1
          csrfID: cookiekey_1
          domainVerificationID: domainverificationkey_1
          idpConfigVerificationID: idpconfigverificationkey_1
        notifications:
          # Email configuration is used for sending verification emails
          email:
            smtpHost: smtp.gmail.com:465
            smtpUser: dummy
            senderAddress: dummy
            senderName: dummy
            tls: true
          # Twilio configuration is used for sending second factor SMS
          twilio:
            senderName: dummy
        # If true, no emails or SMS are sent to users
        debugMode: true
        # ZITADEL pods log level
        logLevel: info
        dns:
          # The main domain, the ZITADEL APIs should be published at
          domain: myzitadel.ch
          # The tls wildcard certificate used for publishing the zitadel endpoints over HTTPS
          tlsSecret: tls-cert-wildcard
          # The subdomains, the ZITADEL APIs should be published at
          subdomains:
            accounts: accounts
            api: api
            console: console
            issuer: issuer
        # This value must match with your cluster DNS
        clusterdns: cluster.local
