services:
  oidcop:
    image: golang:1.24-alpine
    container_name: oidcop
    command: go run main.go
    environment:
      API_URL: 'http://localhost:8080'
      API_DOMAIN: 'localhost:8080'
      PAT_FILE: '/pat/zitadel-admin-sa.pat'
      SCHEMA: 'http'
      HOST: 'localhost'
      PORT: "8004"
    working_dir: /oidc
    ports:
      - 8004:8004
    volumes:
      - "../../pat:/pat"
      - "./:/oidc"
    extra_hosts:
      - "localhost:host-gateway"
