// Code generated by "enumer -type UserState -transform lower -trimprefix UserState -sql"; DO NOT EDIT.

package domain

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _UserStateName = "unspecifiedinitialactiveinactivelockedsuspended"

var _UserStateIndex = [...]uint8{0, 11, 18, 24, 32, 38, 47}

const _UserStateLowerName = "unspecifiedinitialactiveinactivelockedsuspended"

func (i UserState) String() string {
	if i >= UserState(len(_UserStateIndex)-1) {
		return fmt.Sprintf("UserState(%d)", i)
	}
	return _UserStateName[_UserStateIndex[i]:_UserStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UserStateNoOp() {
	var x [1]struct{}
	_ = x[UserStateUnspecified-(0)]
	_ = x[UserStateInitial-(1)]
	_ = x[UserStateActive-(2)]
	_ = x[UserStateInactive-(3)]
	_ = x[UserStateLocked-(4)]
	_ = x[UserStateSuspended-(5)]
}

var _UserStateValues = []UserState{UserStateUnspecified, UserStateInitial, UserStateActive, UserStateInactive, UserStateLocked, UserStateSuspended}

var _UserStateNameToValueMap = map[string]UserState{
	_UserStateName[0:11]:       UserStateUnspecified,
	_UserStateLowerName[0:11]:  UserStateUnspecified,
	_UserStateName[11:18]:      UserStateInitial,
	_UserStateLowerName[11:18]: UserStateInitial,
	_UserStateName[18:24]:      UserStateActive,
	_UserStateLowerName[18:24]: UserStateActive,
	_UserStateName[24:32]:      UserStateInactive,
	_UserStateLowerName[24:32]: UserStateInactive,
	_UserStateName[32:38]:      UserStateLocked,
	_UserStateLowerName[32:38]: UserStateLocked,
	_UserStateName[38:47]:      UserStateSuspended,
	_UserStateLowerName[38:47]: UserStateSuspended,
}

var _UserStateNames = []string{
	_UserStateName[0:11],
	_UserStateName[11:18],
	_UserStateName[18:24],
	_UserStateName[24:32],
	_UserStateName[32:38],
	_UserStateName[38:47],
}

// UserStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UserStateString(s string) (UserState, error) {
	if val, ok := _UserStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UserStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to UserState values", s)
}

// UserStateValues returns all values of the enum
func UserStateValues() []UserState {
	return _UserStateValues
}

// UserStateStrings returns a slice of all String values of the enum
func UserStateStrings() []string {
	strs := make([]string, len(_UserStateNames))
	copy(strs, _UserStateNames)
	return strs
}

// IsAUserState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i UserState) IsAUserState() bool {
	for _, v := range _UserStateValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i UserState) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *UserState) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of UserState: %[1]T(%[1]v)", value)
	}

	val, err := UserStateString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
