services:

  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
    volumes:
      - ../:/workspaces/zitadel:cached
    command: sleep infinity
    working_dir: /workspaces/zitadel
    environment:
      SHELL: /bin/bash
      DEBIAN_FRONTEND: noninteractive
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
      DEVCONTAINER_DB_HOST: db
    ports:
      - "8080:8080"
      - "3000:3000"
      - "4200:4200"

  db:
    image: postgres:18
    restart: unless-stopped
    env_file:
      - ./.env.db
    volumes:
      - db-data-dev:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    ports:
      - 5432:5432

volumes:
  db-data-dev:
