services:
  core-mock:
    image: "${LOGIN_CORE_MOCK_TAG:-login-core-mock:local}"
    container_name: integration-core-mock
    ports:
      - 22220:22220
      - 22222:22222

  login:
    image: "${LOGIN_TAG:-login:local}"
    container_name: integration-login
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - ZITADEL_API_URL=http://core-mock:22222
      - ZITADEL_SERVICE_USER_TOKEN="yolo"
      - EMAIL_VERIFICATION=true

  integration:
    image: "${LOGIN_TEST_INTEGRATION_TAG:-login-test-integration:local}"
    container_name: integration
    environment:
      - LOGIN_BASE_URL=http://login:3001/ui/v2/login
      - CYPRESS_CORE_MOCK_STUBS_URL=http://core-mock:22220/v1/stubs
    depends_on:
      login:
        condition: service_started
      core-mock:
        condition: service_started
