services:
  samlidp:
    image: golang:1.24-alpine
    container_name: samlidp
    command: go run main.go
    environment:
      API_URL: 'http://localhost:8080'
      API_DOMAIN: 'localhost:8080'
      PAT_FILE: '/pat/zitadel-admin-sa.pat'
      SCHEMA: 'http'
      HOST: 'localhost'
      PORT: "8003"
    working_dir: /saml
    ports:
      - 8003:8003
    volumes:
      - "../../pat:/pat"
      - "./:/saml"
    extra_hosts:
      - "localhost:host-gateway"
