services:
  samlsp:
    image: golang:1.24-alpine
    container_name: samlsp
    command: go run main.go
    environment:
      API_URL: 'http://localhost:8080'
      API_DOMAIN: 'localhost:8080'
      PAT_FILE: '/pat/zitadel-admin-sa.pat'
      LOGIN_URL: 'http://localhost:3000'
      IDP_URL: 'http://localhost:3000/saml/v2/metadata'
      HOST: 'http://localhost'
      PORT: '8001'
    working_dir: /saml
    ports:
      - 8001:8001
    volumes:
      - "../pat:/pat"
      - "./:/saml"
    extra_hosts:
      - "localhost:host-gateway"

