// Code generated by protoc-gen-authmethod. DO NOT EDIT.

package auth

import (
	"github.com/caos/zitadel/internal/api/authz"
)

/**
 * AuthService
 */

const AuthService_MethodPrefix = "caos.zitadel.auth.api.v1.AuthService"

var AuthService_AuthMethods = authz.MethodMapping{

	"/caos.zitadel.auth.api.v1.AuthService/GetMyUserSessions": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyUser": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyUserProfile": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/UpdateMyUserProfile": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/ChangeMyUserName": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyUserEmail": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/ChangeMyUserEmail": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/VerifyMyUserEmail": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/ResendMyEmailVerificationMail": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyUserPhone": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/ChangeMyUserPhone": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/RemoveMyUserPhone": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/VerifyMyUserPhone": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/ResendMyPhoneVerificationCode": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyUserAddress": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyUserChanges": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/UpdateMyUserAddress": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyMfas": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/ChangeMyPassword": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyPasswordComplexityPolicy": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/SearchMyExternalIDPs": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/RemoveMyExternalIDP": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/AddMfaOTP": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/VerifyMfaOTP": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/RemoveMfaOTP": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/SearchMyUserGrant": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/SearchMyProjectOrgs": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyZitadelPermissions": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	"/caos.zitadel.auth.api.v1.AuthService/GetMyProjectPermissions": authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},
}
