services:

  proxy-disabled-tls:
    image: "traefik:latest"
    volumes:
      - "./traefik-disabled-tls.yaml:/etc/traefik/traefik.yaml:ro"
    ports:
      - "80:80"
    networks:
      - 'zitadel'
    depends_on:
      zitadel-disabled-tls:
        condition: 'service_healthy'

  proxy-external-tls:
    image: "traefik:latest"
    volumes:
      - "./traefik-external-tls.yaml:/etc/traefik/traefik.yaml:ro"
      - "./selfsigned.crt:/etc/certs/selfsigned.crt:ro"
      - "./selfsigned.key:/etc/certs/selfsigned.key:ro"
    ports:
      - "443:443"
    networks:
      - 'zitadel'
    depends_on:
      zitadel-external-tls:
        condition: 'service_healthy'

  proxy-enabled-tls:
    image: "traefik:latest"
    volumes:
      - "./traefik-enabled-tls.yaml:/etc/traefik/traefik.yaml:ro"
      - "./selfsigned.crt:/etc/certs/selfsigned.crt:ro"
      - "./selfsigned.key:/etc/certs/selfsigned.key:ro"
    ports:
      - "443:443"
    networks:
      - 'zitadel'
    depends_on:
      zitadel-enabled-tls:
        condition: 'service_healthy'

networks:
  zitadel: