log:
  level: "DEBUG"
providers:
  file:
    filename: "/etc/traefik/traefik.yaml"
entrypoints:
  web:
    address: ":80"
http:
  routers:
    zitadel:
      entryPoints:
        - "web"
      service: "zitadel"
      rule: '!PathPrefix(`/ui/v2/login`)'
    login:
      entryPoints:
        - "web"
      service: "login"
      rule: 'PathPrefix(`/ui/v2/login`)'
  services:
    zitadel:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "h2c://zitadel-disabled-tls:8080"
    login:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://login-disabled-tls:3000"