log:
  level: "DEBUG"
providers:
  file:
    filename: "/etc/traefik/traefik.yaml"
entrypoints:
  web:
    address: ":443"
http:
  routers:
    zitadel:
      entryPoints:
        - "web"
      service: "zitadel"
      rule: '!PathPrefix(`/ui/v2/login`)'
      tls: {}
    login:
      entryPoints:
        - "web"
      service: "login"
      rule: 'PathPrefix(`/ui/v2/login`)'
      tls: {}
  services:
    zitadel:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "h2c://zitadel-external-tls:8080"
    login:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://login-external-tls:3000"
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/selfsigned.crt
        keyFile: /etc/certs/selfsigned.key
