log:
  level: "DEBUG"
providers:
  file:
    filename: "/etc/traefik/traefik.yaml"
entrypoints:
  web:
    address: ":443"
http:
  routers:
    zitadel:
      entryPoints:
        - "web"
      service: "zitadel"
      rule: '!PathPrefix(`/ui/v2/login`)'
      tls: {}
    login:
      entryPoints:
        - "web"
      service: "login"
      rule: 'PathPrefix(`/ui/v2/login`)'
      tls: {}
  services:
    zitadel:
      loadBalancer:
        serversTransport: "zitadel"
        passHostHeader: true
        servers:
          - url: "https://zitadel-enabled-tls:8080"
    login:
      loadBalancer:
        serversTransport: "login"
        passHostHeader: true
        servers:
          - url: "http://login-enabled-tls:3000"
  serversTransports:
    zitadel:
      insecureSkipVerify: true
    login:
      insecureSkipVerify: true
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/selfsigned.crt
        keyFile: /etc/certs/selfsigned.key
