*

!constants
!scripts
!src
!public
!locales
!next.config.mjs
!next-env-vars.d.ts
!next-env.d.ts
!tailwind.config.mjs
!postcss.config.cjs
!tsconfig.json
!package.json
!pnpm-lock.yaml

**/*.md
**/*.png
**/node_modules
**/.turbo
**/*.test.ts
**/*.test.tsx