// @generated by protoc-gen-es v1.0.0
// @generated from file zitadel/auth_n_key.proto (package zitadel.authn.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { ObjectDetails } from "./object_pb.js";

/**
 * @generated from enum zitadel.authn.v1.KeyType
 */
export declare enum KeyType {
  /**
   * @generated from enum value: KEY_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: KEY_TYPE_JSON = 1;
   */
  JSON = 1,
}

/**
 * @generated from message zitadel.authn.v1.Key
 */
export declare class Key extends Message<Key> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: zitadel.v1.ObjectDetails details = 2;
   */
  details?: ObjectDetails;

  /**
   * @generated from field: zitadel.authn.v1.KeyType type = 3;
   */
  type: KeyType;

  /**
   * @generated from field: google.protobuf.Timestamp expiration_date = 4;
   */
  expirationDate?: Timestamp;

  constructor(data?: PartialMessage<Key>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "zitadel.authn.v1.Key";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Key;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Key;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Key;

  static equals(a: Key | PlainMessage<Key> | undefined, b: Key | PlainMessage<Key> | undefined): boolean;
}

