name: Check

on: 
  workflow_call: 
    inputs:
      node_version:
        required: true
        type: string
      nx_version:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true
      NX_CLOUD_ACCESS_TOKEN_READONLY:
        required: true

env:
  nx_cache_path: .nx

jobs:
  check:
    name: check
    environment: ${{ github.ref_protected && 'Protected' || '' }}
    runs-on:
      group: zitadel-public
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Fetch main branch
        run: git fetch origin main:main
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "pnpm"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.28.0
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: v2.38.2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install global modules
        run: pnpm add --global nx@${{ inputs.nx_version }} sass
      - name: Install Cypress binary
        run: pnpm cypress install
        working-directory: apps/login
      - uses: nrwl/nx-set-shas@v4
      - name: Run Quality Checks on Affected Projects
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN || secrets.NX_CLOUD_ACCESS_TOKEN_READONLY }}
        run: nx affected --targets lint build test --exclude @zitadel/docs,@zitadel/benchmark
      - name: Test Functional UI Firefox
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN || secrets.NX_CLOUD_ACCESS_TOKEN_READONLY }}
        run: nx affected --targets test-firefox
      - name: Test Functional UI Chrome
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN || secrets.NX_CLOUD_ACCESS_TOKEN_READONLY }}
        run: nx affected --targets test-chrome
      - name: publish coverage
        uses: codecov/codecov-action@v4.3.0
        with:
          file: profile.api.test-unit.cov
          name: api-test-unit
          flags: api-test-unit
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: publish coverage
        uses: codecov/codecov-action@v4.3.0
        with:
          file: profile.api.test-integration.cov
          name: api-test-integration
          flags: api-test-integration
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: functional-ui-tests
          path: |
            tests/functional-ui/cypress/screenshots
            tests/functional-ui/cypress/videos
            tests/functional-ui/cypress/results
      - name: upload race logs
        if: failure() || cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: api-integration-test-race-logs
          path: |
           .artifacts/api-test-integration/race.log.*
